name: lession_01
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.1.0
  grouped_buttons: ^1.0.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/8140.png
    - assets/images/Group.png
    - assets/images/logo1.png
    - assets/images/Welcometoourstore.png
    - assets/images/MaskGroup.png
    - assets/images/Rectangle11.png
    - assets/images/MaskGroup2.png
    - assets/images/illustration.png
    - assets/images/Group3.png
    - assets/images/user1.png
    - assets/images/store1.png
    - assets/images/find.png
    - assets/images/cart.png
    - assets/images/bookmark1.png
    - assets/images/banner.png
    - assets/images/pngfuel1.png
    - assets/images/pngfuel2.png
    - assets/images/pngfuel3.png
    - assets/images/pngfuel4.png
    - assets/images/pngfuel5.png
    - assets/images/pngfuel6.png
    - assets/images/pngfuel7.png
    - assets/images/pngfuel11.png
    - assets/images/pngfuel12.png
    - assets/images/pngfuel13.png
    - assets/images/pngfuel14.png
    - assets/images/imgeUser.png
    - assets/images/Vector11.png
    - assets/images/Vector12.png
    - assets/images/Group6839.png
    - assets/images/card.png
    - assets/images/about_icon.png
    - assets/images/Bell_icon.png
    - assets/images/Delicery_address.png
    - assets/images/Group_6872.png
    - assets/images/help_icon.png
    - assets/images/image_13.png
    - assets/images/My_Details_icon.png
    - assets/images/Orders_icon.png
    - assets/images/Promo_Cord_icon.png
    - assets/images/Vector_icon.png
    - assets/images/Group_6892.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
